executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: host
    json_schema:
      type: string
      minLength: 1
    value: ""
  - handle: username
    json_schema:
      type: string
      minLength: 1
    value: ""
    nullable: false
  - handle: port
    json_schema:
      type: integer
      ui:options:
        step: 1
      minimum: 1
      maximum: 65536
    value: 22
  - handle: authType
    description: ""
    json_schema:
      enum:
        - password
        - privateKey
        - publicKey
      ui:options:
        labels:
          - Password
          - Private Key
          - Public Key
    value: password
  - handle: authValue
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: passphrase
    json_schema:
      contentMediaType: oomol/secret
      type: string
    nullable: true
outputs_def:
  - handle: credential
    json_schema:
      type: object
      additionalProperties: false
      properties:
        host:
          type: string
          minLength: 1
        username:
          type: string
          minLength: 1
        port:
          type: integer
          ui:options:
            step: 1
          minimum: 1
          maximum: 65536
        authType:
          enum:
            - password
            - privateKey
          ui:options:
            labels:
              - Password
              - Private Key
        authValue:
          contentMediaType: oomol/secret
          type: string
        passphrase:
          contentMediaType: oomol/secret
          type: string
title: SSH Credential Config
